### PR TITLE
Scale icons by QT_DEVICE_PIXEL_RATIO

### PR DESCRIPTION
**Pull request by ephemient**
No clue if this is the right thing to do, but it definitely makes things look nicer on my system (dpi is set to 192). Otherwise the xembed icons look freakishly small next to the SNI ones.

### CODE REVIEW

**Comment by davidedmundson** [comment]
I don't see how this makes a difference.

Here we're just scaling before sending, but in the client (in Plasma) the icon will be scaled too.

**Comment by ephemient** [comment]
Maybe that should happen, but it didn't in practice. The 24x24 image being sent across before was being displayed as a little dot centered between normal-sized icons.

**Comment by davidedmundson** [comment]
Then that needs fixing. 
Otherwise we'll have the same problem when an app using SNI directly sends a low res pixmap.

From what I can see the pixmap is sent verbatim to a PlasmaCore.IconItem - which should scale any pixmap set as the source.

**Comment by davidedmundson** [comment]
Could you try with latest master. I put in a fix for chromium

**Comment by FadeMind** [comment]
@davidedmundson  after install lastest git commit default dropbox icon looking:
a

**Comment by ephemient** [comment]
Yeah I think the "problem" I had was just Chromium acting suspiciously different on first embed versus after restarting `xembedsniproxy` or something like that, the appearance at HEAD is fine now. Still encountering #2 but this PR is irrelevant.

**Pull request closed without merging**
